### PR TITLE
Create CAN library based on new CAN architecture

### PR DESCRIPTION
**Pull request by niiquaye**

### CODE REVIEW

**Comment by wmmc88** [comment]
why  is this branch called "cindy can"

**Comment by niiquaye** [comment]
> why is this branch called "cindy can"

This really Cindy's branch I just set it up
for her

**Comment by cindyli-13** [comment]
Changed the title, this PR is for upgrading the sw CAN library to the new CAN architecture

**Comment by wmmc88** [comment]
@cindyli-13  @niiquaye  can someone pick this up?

**Comment by cindyli-13** [comment]
> @cindyli-13 @niiquaye can someone pick this up?

I was supposed to finish this but if anyone would like to pick this up please go ahead :)

**Pull request closed without merging**
