### PR TITLE
first time robot setup

### PR DESCRIPTION
**Pull request by ChengTang62**

### CODE REVIEW

**Comment by Nick-palmar** [comment]
Before we merge I'd like to take a deeper look but for now I just see a bunch of params in two yaml files and some additions to the URDF for autonomy specific things (like the camera and imu). 

Where specifically did you get the params for the yaml files from? I assume you didnt just pull them out of the air?
Also, how do you know we need the changes to the URDF? Has any testing been done to ensure that this is working?

**Comment by ChengTang62** [comment]
Most parameters for navigation stay default for differential drive robot. I changed the parameters that are specifically related to the robot dimension like footprint radius. We can’t merge it yet because I set the position for the camera randomly.

Parameter tuning for navigation happens during testing and would depend on the specific task. If you just refer to if the imu and camera is integrated in the simulation correctly, then yes you can launch the display in gazebo, and they do publish data. But I don’t know if the parameters are the best fit for our rover and task. That would be the next step.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by keyonjerome** [comment]
@ChengTang62 Is there a launch file or procedure you're using for booting this drivetrain URDF into the Gazebo simulation?

**Comment by ChengTang62** [comment]
Not for the rover because there were some issues with the existing urdf that prevent the description from being parsed and I didn’t investigate it. I tested the configuration on a minimum differential drive robot.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nick-palmar** [comment]
Ok so to be clear what does this PR do? Since you say that this is for a differential drive robot that might not be relevant to our rover is it worth merging this code in? Or is this just code that you will be using for testing stuff before you merge in the real stuff? This looks more like test code to me since it seems like you took it from somewhere else and is not tailored to our application - but correct me if I am wrong and we need this in our repo

**Pull request closed without merging**
