### PR TITLE
Basic gazebo simulation

### PR DESCRIPTION
**Pull request by SomeshDaga**
Hi Melvin, I have added two packages, `rover_description` and `rover_simulation`, as previously mentioned for addressing #18 . You can test it out using the following commands:

- `roslaunch rover_simulation empty_world.launch`
- `rostopic pub /rover/arm_bicep_forearm_joint_controller/command std_msgs/Float64 "data: 0.57"` (to move one of the joints as an example)

Please note that the arm layout may be quite different than the actual arm because I still only have a vague idea of it. I think it should be fairly easy to modify the urdfs once we have a clear idea.

Let me know what you think

### CODE REVIEW

**Comment by wmmc88** [comment]
Ok so this is good for the sim

**Comment by wmmc88** [comment]
You will still need to create smth that extends RobotHW to actually implement the reads and writes in the ros control loops tho

**Comment by SomeshDaga** [comment]
@wmmc88 Yeah, I figured as much. I'll leave that to a future set of PRs. Should I leave it to you to merge this PR in?

**Comment by wmmc88** [comment]
@SomeshDaga ya I'll merge it. I just want #24 to go in first.

**Comment by wmmc88** [comment]
@SomeshDaga ya I'll merge it. I just want #24 to go in first.

**Comment by SomeshDaga** [comment]
Build is current failing due to dependency on a new package introduced in https://github.com/uwrobotics/uwrt_mars_rover/pull/26

**Pull request closed without merging**
