### PR TITLE
xbox controller

### LINKED ISSUE #51: xbox controller controls mapping
map xbox buttons and joysticks to various control modes

### PR DESCRIPTION
**Pull request by rayjinghaolei**
closes #51

### CODE REVIEW

**Comment by wmmc88** [comment]
@rayjinghaolei can you push what u have so far

**Comment by wmmc88** [comment]
@rayjinghaolei are you still working on this task?

**Comment by rayjinghaolei** [comment]
I haven't done anything after the qurantine, do you want me to continue to do this task? Would this still useful next year?

**Comment by wmmc88** [comment]
Someone needs to finish it. Let @azumnanji know whether or not you're going to finish this or if someone else should finish it

**Pull request closed without merging**
